// Min egen
package kapitel_13;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

public class LytTilKnap_2 extends JPanel 
{
public static void main(String[] arg)
	{
		JFrame vindue = new JFrame( "Lyt til knap" ); 
		vindue.add( new LytTilKnap_2() );
		vindue.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
		vindue.pack();
		vindue.setVisible(true);
	}
    
    public LytTilKnap_2() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1t1 = new javax.swing.JTextArea();
        jButton1kopierKnap = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2t2 = new javax.swing.JTextArea();

        jTextArea1t1.setColumns(20);
        jTextArea1t1.setRows(5);
        jTextArea1t1.setText("Her er en tekst.\nMarkér noget af \nden og tryk\nKopier...");
        jScrollPane1.setViewportView(jTextArea1t1);

        add(jScrollPane1);

        jButton1kopierKnap.setText("Kopiér>>");
        jButton1kopierKnap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1kopierKnapActionPerformed(evt);
            }
        });
        add(jButton1kopierKnap);

        jTextArea2t2.setColumns(20);
        jTextArea2t2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2t2);

        add(jScrollPane2);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1kopierKnapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1kopierKnapActionPerformed
jTextArea2t2.setText(jTextArea1t1.getSelectedText());        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1kopierKnapActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1kopierKnap;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1t1;
    private javax.swing.JTextArea jTextArea2t2;
    // End of variables declaration//GEN-END:variables
}
