package kapitel_11;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;


public class Grafikpanel extends JPanel 
{
           
    public static void main(String [] arg)
    {
        JFrame vindue = new JFrame( "GrafikpanelMedKomponenter" ); 
		vindue.add( new Grafikpanel() );
		vindue.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
		vindue.setSize(350,300);
		vindue.setVisible(true);
    }
    
    
    
    public void paintComponent(Graphics g)
	{
		super.paintComponent(g);     // tegn baggrunden på panelet
		g.drawLine(0,0,50,50);
		g.fillOval(5,10,300,50);
		g.setColor(Color.GREEN);
                g.drawString("Hej grafiske verden!",100,40);
	}
    
    public Grafikpanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1HvadErDitNavn = new javax.swing.JLabel();
        textField1Navn = new java.awt.TextField();
        jButton1Opdater = new javax.swing.JButton();
        textArea1Hilsen = new java.awt.TextArea();

        setLayout(null);

        jLabel1HvadErDitNavn.setText("Hvad er dit navn?");
        add(jLabel1HvadErDitNavn);
        jLabel1HvadErDitNavn.setBounds(51, 114, 100, 14);

        textField1Navn.setText("Jacob");
        add(textField1Navn);
        textField1Navn.setBounds(150, 110, 41, 20);

        jButton1Opdater.setText("Opdater!");
        jButton1Opdater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1OpdaterActionPerformed(evt);
            }
        });
        jButton1Opdater.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1OpdaterKeyPressed(evt);
            }
        });
        add(jButton1Opdater);
        jButton1Opdater.setBounds(220, 110, 90, 23);

        textArea1Hilsen.setText("Her kommer en tekst...");
        add(textArea1Hilsen);
        textArea1Hilsen.setBounds(50, 140, 260, 80);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1OpdaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1OpdaterActionPerformed
String navn = textField1Navn.getText();
System.out.println("Opdater! navn = " +navn);
textArea1Hilsen.setText("Hej kære "+navn);
repaint();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1OpdaterActionPerformed

    private void jButton1OpdaterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1OpdaterKeyPressed
jButton1Opdater.setMnemonic(KeyEvent.VK_O);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1OpdaterKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Opdater;
    private javax.swing.JLabel jLabel1HvadErDitNavn;
    private java.awt.TextArea textArea1Hilsen;
    private java.awt.TextField textField1Navn;
    // End of variables declaration//GEN-END:variables
}
