//mit eget grafiske program fortsat
package kapitel_11;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;


public class Grafikpanel_2 extends JPanel 
{
public static void main(String[] arg) 
	{
	   JFrame vindue = new JFrame ( "Grafikpanel 2" );
           vindue.add( new Grafikpanel_2() );
           vindue.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
           vindue.setSize(600,300);
           vindue.setVisible(true);         
	}
    
    public Grafikpanel_2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        textField1 = new java.awt.TextField();
        textArea1 = new java.awt.TextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        textField1.setText("En TextField");
        add(textField1);

        textArea1.setText("Et TextArea");
        add(textArea1);

        jLabel1.setText("En Label");
        add(jLabel1);

        jButton1.setText("OK");
        add(jButton1);

        jCheckBox1.setText("En");
        add(jCheckBox1);

        jCheckBox2.setText("To");
        add(jCheckBox2);

        jCheckBox3.setText("Tre");
        add(jCheckBox3);

        jRadioButton1.setText("Radio1");
        add(jRadioButton1);

        jRadioButton2.setText("Radio 2");
        add(jRadioButton2);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ComboBox Rød", "ComboBox Grøn", "ComboBox Blå" }));
        jComboBox1.setToolTipText("");
        add(jComboBox1);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "List rød", "List grøn", "List Blå" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.TextArea textArea1;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
